### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by bballboy8** [bballboy8/cozy-corners-fe#8]
https://github.com/bballboy8/cozy-corners-fe/blob/2d0e29d03eb517d43c5373c058ad2d305c83fd18/src/components/Payment.js#L22

I'm concerned with storing these in state. We need to consider better security here

**Comment by chirag-456** [comment]
That is used to show the error if any of the column is blanked when we submit on pay button, Here I am checking the attributes of the form.
